In [1]:
import pandas as pd

In [4]:
from DataFrameFromFile import load_data
file_name = "knesset_25.xlsx"
df_from_file = load_data(file_name)
df_from_file

,city_name,ballot_code,party_avoda,party_shahar_kalkali_hadash,party_bayit_yehudi,party_agudat_israel,party_daled,party_vavmem,party_shahar_koach_hevrati,party_kama,...,party_tze'irim_bo'arim,party_manhigut_hevratit,party_kol_hasviva_vehachai,party_halev_hayehudi,party_seder_chadash,party_kol,party_beometz_bishvilech,party_kavod_umasoret,party_shas,party_daat_tov_vera
0,אבו גווייעד שבט,3.1,0,0,0,0,4,21,0,0,...,0,0,0,0,0,0,0,0,0,2
1,אבו גווייעד שבט,3.2,1,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,1
2,אבו גווייעד שבט,3.3,0,0,0,0,0,12,0,0,...,0,0,0,0,0,0,0,0,2,0
3,אבו גווייעד שבט,3.4,0,0,0,0,0,3,0,0,...,1,0,0,0,0,0,0,0,2,0
4,אבו גוש,1.1,1,0,0,0,171,43,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12540,תקוע,3.0,4,3,66,1,0,1,0,0,...,1,0,0,0,0,0,6,0,12,0
12541,תקוע,4.0,6,3,66,3,0,0,0,0,...,0,0,0,1,0,0,1,0,3,0
12542,תראבין אצאנע שבט,1.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
12543,תראבין אצאנעישוב,1.0,1,0,0,0,6,1,0,0,...,0,0,0,0,0,0,1,0,1,0
12544,תרום,1.0,5,4,17,12,0,0,0,0,...,1,0,0,0,0,0,4,0,49,0

In [21]:
def group_and_aggregate_data(df: pd.DataFrame, group_by_column: str, agg_func) -> pd.DataFrame:
    try:
        agg_func = agg_func if isinstance(agg_func, str) else agg_func.__name__
        return df.drop(columns='ballot_code').groupby(group_by_column).aggregate(agg_func)
    except Exception as e:
        print(f"not a aggregate function: {e}")
        return pd.DataFrame()

In [44]:
aggregated_df = group_and_aggregate_data(load_data("knesset_25.xlsx"), "city_name", "sum")
aggregated_df

,party_avoda,party_shahar_kalkali_hadash,party_bayit_yehudi,party_agudat_israel,party_daled,party_vavmem,party_shahar_koach_hevrati,party_kama,party_koach_lehashpia,party_tzomet,...,party_tze'irim_bo'arim,party_manhigut_hevratit,party_kol_hasviva_vehachai,party_halev_hayehudi,party_seder_chadash,party_kol,party_beometz_bishvilech,party_kavod_umasoret,party_shas,party_daat_tov_vera
city_name,,,,,,,,,,,,,,,,,,,,,
אבו גווייעד שבט,1,0,0,0,4,38,0,0,1,0,...,1,0,0,0,0,0,0,0,4,3
אבו גוש,14,1,1,3,1263,312,0,0,0,0,...,2,7,1,0,1,1,3,0,4,0
אבו סנאן,34,0,3,0,677,2030,4,1,2,0,...,1,4,1,3,1,6,9,0,12,1
אבו עבדון שבט,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
אבו קורינאת שבט,5,0,1,0,10,65,0,0,1,1,...,0,1,0,0,2,1,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
תקומה,3,2,42,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,13,0
תקוע,25,18,266,13,0,1,0,0,0,0,...,1,1,1,3,0,0,26,0,27,0
תראבין אצאנע שבט,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
תראבין אצאנעישוב,1,0,0,0,6,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
תרום,5,4,17,12,0,0,0,0,0,0,...,1,0,0,0,0,0,4,0,49,0

In [76]:
def remove_sparse_columns(df: pd.DataFrame, threshold: int) -> pd.DataFrame:
     return df[df.sum()[df.sum() > threshold].index]

In [91]:
result = remove_sparse_columns(aggregated_df, threshold=1000000)
result

                  party_likud
city_name
אבו גווייעד שבט            12
אבו גוש                   208
אבו סנאן                  405
אבו עבדון שבט               0
אבו קורינאת שבט             9
...                       ...
תקומה                     142
תקוע                      353
תראבין אצאנע שבט           28
תראבין אצאנעישוב          143
תרום                      201

[1216 rows x 1 columns]

In [5]:
from PCA import dimensionality_reduction
file_name = "knesset_25.xlsx"
df_from_file = load_data(file_name)
meta_columns_list = ['city_name', 'ballot_code']
manual_pca_df_from_file = dimensionality_reduction(df_from_file, 2, meta_columns_list)
manual_pca_df_from_file

              city_name  ballot_code       PC1       PC2
0       אבו גווייעד שבט          3.1  2.974618 -0.445342
1       אבו גווייעד שבט          3.2  2.615395 -0.278371
2       אבו גווייעד שבט          3.3  3.054359 -0.698460
3       אבו גווייעד שבט          3.4  2.618881 -0.273326
4               אבו גוש          1.1  5.006838 -2.709690
...                 ...          ...       ...       ...
12540              תקוע          3.0 -1.592078  2.034263
12541              תקוע          4.0 -0.725699  2.682996
12542  תראבין אצאנע שבט          1.0  2.269919 -0.050803
12543  תראבין אצאנעישוב          1.0  1.978971  0.124691
12544              תרום          1.0 -1.594112  2.097958

[12545 rows x 4 columns]

In [6]:
print("next")

next