In [1]:
import pandas as pd
import numpy as np
import streamlit as st
from dask.dataframe.methods import drop_columns

In [2]:
def load_data(filepath: str) -> pd.DataFrame:
    try :
        if filepath[-3:] == 'csv':
            return pd.read_csv(filepath)
        elif filepath[-4:] == 'xlsx' or filepath[-3:] == 'xls':
            return pd.read_excel(filepath)
    except Exception as e:
        print(f"Error reading file {filepath}: {e}")
        return pd.DataFrame()

In [21]:
def group_and_aggregate_data(df: pd.DataFrame, group_by_column: str, agg_func) -> pd.DataFrame:
    try:
        agg_func = agg_func if isinstance(agg_func, str) else agg_func.__name__
        return df.drop(columns='ballot_code').groupby(group_by_column).aggregate(agg_func)
    except Exception as e:
        print(f"not a aggregate function: {e}")
        return pd.DataFrame()

In [44]:
df = group_and_aggregate_data(load_data("knesset_25.xlsx"), "city_name", "sum")
df

,party_avoda,party_shahar_kalkali_hadash,party_bayit_yehudi,party_agudat_israel,party_daled,party_vavmem,party_shahar_koach_hevrati,party_kama,party_koach_lehashpia,party_tzomet,...,party_tze'irim_bo'arim,party_manhigut_hevratit,party_kol_hasviva_vehachai,party_halev_hayehudi,party_seder_chadash,party_kol,party_beometz_bishvilech,party_kavod_umasoret,party_shas,party_daat_tov_vera
city_name,,,,,,,,,,,,,,,,,,,,,
אבו גווייעד שבט,1,0,0,0,4,38,0,0,1,0,...,1,0,0,0,0,0,0,0,4,3
אבו גוש,14,1,1,3,1263,312,0,0,0,0,...,2,7,1,0,1,1,3,0,4,0
אבו סנאן,34,0,3,0,677,2030,4,1,2,0,...,1,4,1,3,1,6,9,0,12,1
אבו עבדון שבט,0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
אבו קורינאת שבט,5,0,1,0,10,65,0,0,1,1,...,0,1,0,0,2,1,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
תקומה,3,2,42,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,13,0
תקוע,25,18,266,13,0,1,0,0,0,0,...,1,1,1,3,0,0,26,0,27,0
תראבין אצאנע שבט,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
תראבין אצאנעישוב,1,0,0,0,6,1,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
תרום,5,4,17,12,0,0,0,0,0,0,...,1,0,0,0,0,0,4,0,49,0

In [76]:
def remove_sparse_columns(df: pd.DataFrame, threshold: int) -> pd.DataFrame:
     return df[df.sum()[df.sum() > threshold].index]

In [91]:
result = remove_sparse_columns(df, threshold=1000000)
result

                  party_likud
city_name
אבו גווייעד שבט            12
אבו גוש                   208
אבו סנאן                  405
אבו עבדון שבט               0
אבו קורינאת שבט             9
...                       ...
תקומה                     142
תקוע                      353
תראבין אצאנע שבט           28
תראבין אצאנעישוב          143
תרום                      201

[1216 rows x 1 columns]